- name: Load elastic password from control node file
  set_fact:
    elastic_password: "{{ lookup('file', '/home/goad/elastic_password.txt') | trim }}"

- name: Check if Elastic Agent service exists
  ansible.windows.win_service_info:
    name: Elastic Agent
  register: agent_service

- name: install elastic agent
  win_shell: C:\Temp\Agent\elastic-agent-9.0.3-windows-x86_64\elastic-agent.exe install --non-interactive
  when: agent_service.exists == false

- name: make installation directory
  win_file:
    path: C:\Temp\Agent\
    state: directory
  when: agent_service.exists == false

- name: download elastic agent
  win_get_url: 
    url: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-9.0.3-windows-x86_64.zip
    dest: C:\Temp\Agent\elastic-agent-9.0.3-windows-x86_64.zip
  when: agent_service.exists == false

- name: unzip elastic agent
  win_unzip: 
    src: C:\Temp\Agent\elastic-agent-9.0.3-windows-x86_64.zip
    dest: C:\Temp\Agent\
  when: agent_service.exists == false

- name: copy over agent config
  template:
    src: elastic-agent.yml
    dest: C:\Program Files\Elastic\Agent\elastic-agent.yml
  vars:
    elastic_password: "{{ elastic_password }}"

- name: restart elastic agent
  ansible.windows.win_service:
    name: "Elastic Agent"
    state: restarted
