- name: Create Local admin connections group 
  scicore.guacamole.guacamole_connections_group:
    base_url: "{{guac_url}}"
    auth_username: "{{guacadmin_username}}"
    auth_password: "{{guacadmin_password}}"
    group_name: "{{domain_name}}-LOCAL"

# LOCAL ADMIN
- name: Add Local RDP Admin connection
  scicore.guacamole.guacamole_connection:
    base_url: "{{guac_url}}"
    rdp_domain: "."
    auth_username: "{{guacadmin_username}}"
    auth_password: "{{guacadmin_password}}"
    connection_name: "RDP-{{item.key}}-{{item.value.hostname}}-localadmin"
    protocol: "rdp"
    hostname: "{{hostvars[item.key].ansible_host}}"
    port: "3389"
    username: "{{admin_user}}"
    password: "{{ item.value.local_admin_password }}"
    rdp_server_layout: "{{layout}}"
    rdp_ignore_server_certs: true
    validate_certs: false
    max_connections: 4
    group_name: "{{domain_name}}-LOCAL"
  when: item.value.os | default('') in ['', 'windows'] and hostvars[item.key] is defined
  with_dict: "{{hosts}}"

- name: Add RDP local admin to list of connections
  set_fact:
    "connection_list": "{{ connection_list | default([]) + ['RDP-' + item.key + '-' + item.value.hostname + '-localadmin']}}"
  with_dict: "{{hosts}}"

- name: Add Local SSH connection
  scicore.guacamole.guacamole_connection:
    base_url: "{{guac_url}}"
    auth_username: "{{guacadmin_username}}"
    auth_password: "{{guacadmin_password}}"
    connection_name: "SSH-{{item.key}}-{{item.value.hostname}}-localadmin"
    protocol: "ssh"
    hostname: "{{hostvars[item.key].ansible_host}}"
    port: "22"
    username: "{{admin_user}}"
    password: "{{ item.value.local_admin_password }}"
    validate_certs: false
    max_connections: 4
    group_name: "{{domain_name}}-LOCAL"
  when: item.value.os is defined and item.value.os == "linux" and hostvars[item.key] is defined
  with_dict: "{{hosts}}"

- name: Add SSH local admin to list of connections
  set_fact:
    "connection_list": "{{ connection_list | default([]) + ['SSH-' + item.key + '-' + item.value.hostname + '-localadmin']}}"
  with_dict: "{{hosts}}"

# # VNC
# - name: Create VNC connections group 
#   scicore.guacamole.guacamole_connections_group:
#     base_url: "{{guac_url}}"
#     auth_username: "{{guacadmin_username}}"
#     auth_password: "{{guacadmin_password}}"
#     group_name: "{{domain_name}}-VNC"
# 
# - name: Add VNC connection
#   scicore.guacamole.guacamole_connection:
#     base_url: "{{guac_url}}"
#     auth_username: "{{guacadmin_username}}"
#     auth_password: "{{guacadmin_password}}"
#     connection_name: "VNC-{{item.key}}-{{item.value.hostname}}"
#     protocol: "vnc"
#     hostname: "{{hostvars[item.key].ansible_host}}"
#     port: "5900"
#     username: ""
#     password: "{{ vnc_password }}"
#     group_name: "{{domain_name}}-VNC"
#   when: item.value.os == "windows"
#   with_dict: "{{hosts}}"
# 
# - name: Add VNC  to list of connections
#   set_fact:
#     "connection_list": "{{ connection_list | default([]) + ['VNC-' + item.key + '-' + item.value.hostname ]}}"
#   with_dict: "{{hosts}}"

# Domain users
- name: Create domain connections groups (one group by domain)
  scicore.guacamole.guacamole_connections_group:
    base_url: "{{guac_url}}"
    auth_username: "{{guacadmin_username}}"
    auth_password: "{{guacadmin_password}}"
    group_name: "{{domain_data.key}}"
  loop: "{{ domains | dict2items }}"
  loop_control:
    loop_var: domain_data

- name: Iterate over users in each domain
  include_tasks: users_iterate.yml
  vars:
    users_domain_name: "{{domain_data.key}}"
    users: "{{domain_data.value.users}}"
    hosts_list: "{{hosts}}"
  loop: "{{ domains | dict2items }}"
  loop_control:
    loop_var: domain_data

- name: Add guacamole user
  scicore.guacamole.guacamole_user:
    base_url: "{{guac_url}}"
    auth_username: "{{guacadmin_username}}"
    auth_password: "{{guacadmin_password}}"
    username: "{{ item.name }}"
    password: "{{ item.pass }}"
    allowed_connections: "{{connection_list |list}}"
    organization: company_bar
  with_items:
    - "{{guacamole_users}}"
