# LOGS and Monitoring ==========================================================================================
- name: Install ELK
  hosts: elk_server
  become: yes
  roles:
    - { role: 'elk', tags: 'elk' }

# Temporaril disable logstash installation as we need to upgrade to elastic agent
# - name: Install log agent on windows vms
#   hosts: elk_log
#   roles:
#     - { role: 'logs_windows', tags: 'agent' }
